/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e9d7f4a78aa6d52894a5fb5e2665efb2)
interface __BaseEnv_Env {
	DB: D1Database;
	AI: Ai;
	ASSETS: Fetcher;
	APP_ENV: "production" | "development";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		DB: D1Database;
		AI: Ai;
		ASSETS: Fetcher;
		APP_ENV: "production";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV">> {}
}
